### ISSUE TITLE
Notebook to visualize gini coefficient

### ISSUE THREAD

**Issue by Dianadec** [bcgov/cas-notebooks#10]
looking to see how the gini coefficient in BC compares to Canada as a whole as well as Atlantic Provinces, QC, ON, Prairie (not including AB), AB.

Reference period 1990-current.

Income concepts: adjusted market income, adjusted total income, adjusted after-tax income.

The data sets are here: https://www150.statcan.gc.ca/t1/tbl1/en/cv.action?pid=1110013401.

You can download a CSV with the data mentioned above.

**Comment by matthieu-foucault** [comment]
@Maralsotoudehnia a notebook was added in this repo. To view it, you can go to: https://nbviewer.jupyter.org/github/bcgov/cas-notebooks/blob/e406ccdaf9007881aabf6fa5fe2ffe32d3e7fe87/CanadaGini.ipynb

The notebook view shows all of the code needed to produce the plots, which allows easy reuse and peer review. 

If you want to only share the plots, you can export png images by hovering on them and clicking on the camera icon
![image](https://user-images.githubusercontent.com/2684022/123718849-098c7b80-d835-11eb-9282-e8a94634dd2b.png)

Note that the data did not have a series for the "Prairie provinces without Alberta", as asked in the issue.

**Comment by Maralsotoudehnia** [comment]
Nice work @matthieu-foucault! Thanks!
